### ISSUE TITLE
still getting "Message too long" in repl

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#108]
On branch Develop, commit 1bda2c3:

``` clojure
some-namespace=> (print-table (:members (reflect "")))
System.Net.Sockets.SocketException: Message too long
```

**Comment by timsgardner** [comment]
Pretty sure we can do this by just sending the repl output in pulses to the client, right?

**Comment by nasser** [comment]
That won't work with the current UDP architecture because order is not guaranteed. The solution is short lived TCP REPL sessions.

1. Client has some code to send
2. Client opens new TCP socket to Arcadia is opened
3. Client sends code over socket
4. Arcadia receives code, can be multiple packets in size
5. Arcadia evaluates code
6. Arcadia sends result back over socket
7. Client receives code, can be multiple packets in size
8. Client closes socket

The trick is to open and close the socket right away. That way, the REPL does not go down in the event of an VM flush, the way our old long lived TCP REPL did. I'll get on it.

**Comment by timsgardner** [comment]
The solution is "<EOF>"

**Comment by timsgardner** [comment]
I like how robust the UDP architecture is, though. The worst that can happen if things get stuck is you have to kill the client repl and run the repl command again, you start back up just where you left off. Is there an easy way to get a similar property with TCP?

**Comment by nasser** [comment]
I believe so.

**Comment by timsgardner** [comment]
cool

**Comment by nasser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pass Through Socket REPL](https://trello.com/c/M1b73QrP/1-pass-through-socket-repl)

**Comment by nasser** [comment]
The legacy UDP REPL that experienced this issue has been removed from the beta branch and replaced with the Socket REPL and nREPL, neither of which exhibit this behavior.
