### ISSUE TITLE
Editor Crashes if exited before manually stopping repl

### ISSUE THREAD

**Issue by Mechrophile** [arcadia-unity/Arcadia#157]
reproduce
windows 10, Unity 5.3.5f1
create new project, 3d.
Enable Run in Background
.NET 2.0

cd path/to/assets
git clone arcadia
cd assets
git checkout develop

return to editor. Import is displayed, shows Arcadia Started!

attempt to exit the editor via x in upper right.

Editor crashes.

Crash occurs every time editor is closed without stopping repl manually
[Editor-crash.txt](https://github.com/arcadia-unity/Arcadia/files/404143/Editor-crash.txt)

**Comment by selfsame** [comment]
confirming for windows vista/7

**Comment by selfsame** [comment]
via @worrel with procmon

https://www.dropbox.com/s/c7pz46yjpi7pblr/unity-wait-chain-on-freeze.PNG?dl=0

**Comment by selfsame** [comment]
an instance of the following class will close the repl when quitting the editor in windows and prevent this issue:

```cs
[ExecuteInEditMode]
public class REPLKiller : ScriptableObject
{
    void OnDestroy() //called when unity editor is closing
    {
        Repl.StopREPL();
    }
}
```

(instanced by `var killer = ScriptableObject.CreateInstance<REPLKiller>();`)

However, these instances will get an OnDestroy() message when transitioning between edit/play mode.  Since this happens after the Arcadia initialization it effectively prevents arcadia's auto repl start feature.
