### ISSUE TITLE
hook- not working -- use DestroyImmediate in edit mode

### ISSUE THREAD

**Issue by Mechrophile** [arcadia-unity/Arcadia#160]
Windows 10
Unity 5.3.x

calling hook- from the repl causes the following:
![image](https://cloud.githubusercontent.com/assets/2494198/17527007/aa005348-5e37-11e6-85aa-326cb4567960.png)

and the hook is not removed.

**Comment by timsgardner** [comment]
Seems to me we can't avoid some policy on `Destroy` vs `DestroyImmediate`, which probably requires solving the old problem of detecting edit vs play mode, in a deployed app vs in the editor. Unless I'm missing something.

**Comment by Mechrophile** [comment]
I think the ticket is mostly to point out that "(a/hook-)" does nothing while in edit mode.  Your statement still stands, and I do most of my work in play mode now anyway, but maybe its just a matter of a better error message.

**Comment by nasser** [comment]
Yeah the `Destroy`/`DestroyImmediate` thing is such a nightmare and keeps cropping up. I will dig back into it and see if I can get assemble a matrix of situations code can be evaluated in, how to detect that mode, and which destroy to use.

**Comment by timsgardner** [comment]
for `cmpt-` specifically, is there anything wrong with just saying it's `Destroy` in play mode, `DestroyImmediate` in edit?

**Comment by timsgardner** [comment]
Though part of me wants everything to just be `DestroyImmediate`

**Comment by nasser** [comment]
We could try that. As I understand `DestroyImmediate` sets the object to Unity's fake null immediately, while `Destroy` does it at the end of the frame (or after a number of seconds elapse if you pass in a second parameter). If `destroy` mapped to `DestroyImmediate` and `destroy-deferred` mapped to `Destroy`, maybe we'd have a `destroy` function that Just Works in all contexts?

From what I gather Unity doesn't like people using `DestroyImmediate` because `Destroy` lets them batch all `Destroy`s at the end of the frame, but maybe that's ok?

**Comment by timsgardner** [comment]
My guess was/is that Unity doesn't like `DestroyImmediate` in play contexts because it potentially fucks with the ordering logic of the event system. Perhaps it's possible to `DestroyImmediate` a component which Unity then calls an event on later in the frame, for example. If so that might be a more compelling reason not to use it.
But maybe we don't care?  The options seem to be:

1. `destroy` function, which calls `Destroy` in play mode and `DestroyImmediate` in editor mode
- `destroy` function, which calls `DestroyImmediate` in play mode and editor mode, and `destroy-deferred` function, which calls `Destroy` in play mode and editor mode
- `destroy` function which calls `DestroyImmediate` in play mode and editor mode;  `destroy-deferred` function, which calls `Destroy` in play mode and editor mode; and `destroy-dwim` or `destroy-adaptive` or something function, that calls `Destroy` in Play mode and `DestroyImmediate` in EditorMode
- 2 and 3, except `destroy` always calls `Destroy`, and we have another function `destroy-now` or just `destroy-immediate`, which calls `DestroyImmediate`

`UnityStatusHelper.cs`, introduced in 5aab401ba73d8bed2fe138510ba7f35014b8391b, might help with some of this.

**Comment by timsgardner** [comment]
I sort of like 4

**Comment by nasser** [comment]
I like how explicit 4 is. If we can come up with a better name for the automatic version, I am sold. `destroy-auto`? `destroy-automatic`? `auto-destroy`?

**Comment by timsgardner** [comment]
`maybe-destroy??`

**Comment by timsgardner** [comment]
and then have another one called `destroy-maybe???` that does something completely different

**Comment by nasser** [comment]
`destroy1` `destroy2` `destroy-real1`

**Comment by timsgardner** [comment]
Two of these are just wrappers, which we're trying to veer away from unless there's a really really good reason for inclusion; in this case perhaps there is. The adaptive version is our own thing.

The main reason an adaptive version is desirable is for live programming, which can happen in Edit mode or in Play mode. We want to be able to use the same code in both cases if possible, an adaptive destroy would help with that. So then the next question (so far as naming is concerned) is what the meaning of this function is. 

I'm receptive to "automatic", "auto", etc, but I also feel like everything a computer does is automatic on some level, and it doesn't really get us closer to describing the meaning of the function.

I'd say the meaning of the function is that an object leaves the scene at the next convenient moment. One possibility for a name is `exit`, as in "exit stage left", which works with the scene metaphor, but is a somewhat scary word in a program; one way to mitigate that might be the slightly weirder but even more theatery `exists` ("Banquo exits stage left"). Another option is `retire`, which has the benefit of connoting both graceful withdrawal and the Bladerunner euphemism for destruction.

**Comment by timsgardner** [comment]
(I like `retire`)

**Comment by timsgardner** [comment]
closed as of 0278756d44a0c1ded87f3a4a0099b9981fee8f8b
