### ISSUE TITLE
Automatically Adjust Unity's Settings

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#165]
For .NET subset and the like. This used to work, but broke for some reason.

**Comment by timsgardner** [comment]
While we're at it, we should print some visible indication that we're doing that to the console or something. It's unnerving when a library takes it upon itself to change project settings, makes a person wonder what else it might be up to.

Some projects also presumably depend on or expect those settings being in a state incompatible with Arcadia (otherwise why have the settings?); if we break someone's Unity project by changing their settings, we should let them know it was us.

**Comment by nasser** [comment]
Agreed.

**Comment by nasser** [comment]
So the code to do this and inform the user has been in there for a while, I think what has changed (why it stopped working) is because the `Initialization` class started depending on Clojure recently, which means that if the Mono level is .NET subset loading `Initialization` fails before it has a chance to adjust any settings. Options include

1. Remove `clojure.lang` dependency from `Initialization`. This would involve moving all calls involving RT into other classes
2. Moving settings adjustment into its own class that adjusts settings first then triggers `Initialization`

**Comment by nasser** [comment]
Fixed in f3e13587922fb72d89a97d6750f8f1d58ecfcdd9
