### ISSUE TITLE
repl printing unity stuff cryptically

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#166]
I know it's nice for serialization but

``` clojure
#unity/Object -20950
```

is very mysterious in a repl, with no way to know if it's a GameObject or a Component or what. We used to print the name and type information etc of GameObjects - the representation we get from `(str some-object)`. Would be nice to have a way of getting that info again, or switching off this form in the repl – possibly switch on `clojure.core/*print-dup*`?

**Comment by nasser** [comment]
There are two approaches I can think of: 

1. Make the serialized form of Unity objects more readable
2. Keep it as is, but use a readable serializer in the REPL

To make 1 happen, we could serialize as `#unity/Transform -978`, `#unity/GameObject -57948` and so on? We can generate a separate data reader for each Unity type to do that.

To make 2 happen, we'd need a way to swap out the printer when things are being printed in the REPL. This is tricky because it interacts with the `*object-db*` dance we need in order to serialize properly. Not intractable, though.

**Comment by selfsame** [comment]
why not have a junk field ignored by the reader?

```clj
#unity/Object [Transform -20950]
```

**Comment by nasser** [comment]
That could work, too. `(str obj)` gives you a bit more, e.g. the "name" of the object as well. @timsgardner do you think a junk field is enough context for the REPL?

**Comment by timsgardner** [comment]
Hm maybe a junk field (or two) would do the trick. I think in normal clojure there is indeed a distinction between forms that can be serialized and forms that print legibly in the normal course of things, which is what `*print-dup*` is for, and there is normally no particular expectation that a form printed in the repl will be readable by the repl, even if it's a representation of a clojure data structure. But if there's an easy way to support both cases with a single form, I guess we might as well? The only drawback I can think of for a junk field is that it seems sort of degenerate from a data perspective, since #unity/Object [Transform -20950] would equal #unity/Object [FlubsoTheWatermelonBandit -20950], and it would make serialized representations more lengthy.

**Comment by nasser** [comment]
Yeah the current implementation of literals is based on `print-method`, not sure why. I will port it over to `*print-dup*` and rework things to make it switchable. `#unity/Object -982` is great for serialization, and maybe we can do the lengthier junk field for the REPL? `#unity/Object [Transform "GameObject Clone (1)" -409382]`?

**Comment by timsgardner** [comment]
This got fixed somewhere along the line
