### ISSUE TITLE
packages in linux

### ISSUE THREAD

**Issue by timsgardner** [arcadia-unity/Arcadia#175]
packages in linux dunt wrk

**Comment by selfsame** [comment]
To clarify - this was an issue with the "https://" meta links not working in linux and windows

**Comment by nasser** [comment]
* Easy fix: use `http` instead.
* Correct fix: Get Mono's SSL to work on Linux (and Windows, I think). This would involve [more than zero lines of code](http://www.mono-project.com/docs/faq/security/).

I am nervous about implementing the easy/insecure stopgap and having that be The Fix for a while. This is the kind of thing we should get right from day one, maybe, even though that will mean unusable packages outside of OSX for a little longer.

**Comment by timsgardner** [comment]
Does this problem also apply to windows?

**Comment by selfsame** [comment]
yes both windows and linux have this issue.

**Comment by nasser** [comment]
The concern is the former. We should just do it right from the start. I'll get on it.

**Comment by selfsame** [comment]
appears to be fixed after running https://gist.github.com/nasser/306f016cfec3c5f9c01e1fd85c7da67a

**Comment by nasser** [comment]
Thanks for testing @selfsame. Can you tell me where `mozroots.exe` is on Linux and Windows?

**Comment by selfsame** [comment]
`/home/selfsame/unity-editor-2017.1.0xf3Linux/Editor/Data/MonoBleedingEdge/lib/mono/4.5/mozroots.exe`

`Program Files/Unity/Editor/Data/Mono/bin/mozroots`

imagine these could change between unity versions though :(

**Comment by nasser** [comment]
Thanks! I don't really expect them to change, to be honest. They're part of the Mono distribution and that's more or less fixed, I think.

**Comment by nasser** [comment]
Fixed as of 059d591
