### ISSUE TITLE
Return removed functions from hook- and hook-clear

### ISSUE THREAD

**Issue by nasser** [arcadia-unity/Arcadia#180]
Right now we return the target object. Any good reason for this?

**Comment by timsgardner** [comment]
I think you wrote that function, right? Do you remember the rationale?

Reasons for returning the object might include the observation that that's generally the way things are done in OOP systems to enable method chaining, or, in our case, the `->`  macro. This is just syntactic sugar however, the need for which is obviated by `doto`.

Putting that aside, the biggest reason I can think of not to return the functions is that it might entail an allocation, though I guess some of that's probably going on internally anyway when we modify the map holding the functions.

`cmpt+` returns the component (which it has to do, no other clean way to get it).
`cmpt-`, however, returns nil, because destroyed components shouldn't be anything. It could return the object I suppose, but it's a little weird for `cmpt+` to return the component and `cmpt-` to return the object.

**Comment by nasser** [comment]
I did write it, can't remember why I did the target object thing. I feel like returning the object or nil makes the most sense, and its better to return something rather than nothing? I don't think it should incur an allocation.

**Comment by timsgardner** [comment]
If hook- or hook-clear clear can multiple functions we'd have to return a collection, and if we want to do it cleanly we'd have to return a collection every time, not just when there's more than one cleared function; hence the allocation

**Comment by timsgardner** [comment]
I'm also not sure if it's best to return something rather than nothing, if it leads to a less consistent API

**Comment by selfsame** [comment]
I think either return a boolean whether something was successfully removed or just nil a la `GameObject/Destroy`

**Comment by nasser** [comment]
Maybe nil is fine to match `cmpt-`. Its easy, consistent, does not allocate, and if it proves to be a problem we can deal with it then.

**Comment by timsgardner** [comment]
Sounds good.
