### ISSUE TITLE
Can't serialize vars in state

### ISSUE THREAD

**Issue by Saikyun** [arcadia-unity/Arcadia#366]
When I do this in editor mode:

```
(state+ (object-named "Main Camera") :what #'log)
```

Then press play, I get this in the debug console:

```
InvalidOperationException: No dispatch macro for: '
clojure.lang.EdnReader+DispatchReader.Read (clojure.lang.PushbackTextReader r, System.Char hash, System.Object opts) (at <fb1204dbf0b848beaab1559f81f1b22c>:0)
clojure.lang.EdnReader+ReaderBase.invoke (System.Object arg1, System.Object arg2, System.Object arg3) (at <fb1204dbf0b848beaab1559f81f1b22c>:0)
clojure.lang.EdnReader.ReadDelimitedList (System.Char delim, clojure.lang.PushbackTextReader r, System.Boolean isRecursive, System.Object opts) (at <fb1204dbf0b848beaab1559f81f1b22c>:0)
clojure.lang.EdnReader+MapReader.Read (clojure.lang.PushbackTextReader r, System.Char leftbrace, System.Object opts) (at <fb1204dbf0b848beaab1559f81f1b22c>:0)
clojure.lang.EdnReader+ReaderBase.invoke (System.Object arg1, System.Object arg2, System.Object arg3) (at <fb1204dbf0b848beaab1559f81f1b22c>:0)
clojure.lang.EdnReader.read (clojure.lang.PushbackTextReader r, System.Boolean eofIsError, System.Object eofValue, System.Boolean isRecursive, System.Object opts) (at <fb1204dbf0b848beaab1559f81f1b22c>:0)
clojure.lang.EdnReader.read (clojure.lang.PushbackTextReader r, clojure.lang.IPersistentMap opts) (at <fb1204dbf0b848beaab1559f81f1b22c>:0)
clojure.lang.EdnReader.readString (System.String s, clojure.lang.IPersistentMap opts) (at <fb1204dbf0b848beaab1559f81f1b22c>:0)
clojure$edn$read_string__40662.invokeStatic (System.Object , System.Object ) (at <4136a6fc2e834b2682ca53c53aa30c84>:0)
clojure$edn$read_string__40662.invoke (System.Object , System.Object ) (at <4136a6fc2e834b2682ca53c53aa30c84>:0)
arcadia$internal$state_help$deserialize__72.invokeStatic (System.Object ) (at <0a4786b4710342d48a9beab93a6204c3>:0)
Rethrow as Exception: wrapper
arcadia$internal$state_help$deserialize__72.invokeStatic (System.Object ) (at <0a4786b4710342d48a9beab93a6204c3>:0)
arcadia$internal$state_help$deserialize__72.invoke (System.Object ) (at <0a4786b4710342d48a9beab93a6204c3>:0)
clojure.lang.Var.invoke (System.Object arg1) (at <fb1204dbf0b848beaab1559f81f1b22c>:0)
ArcadiaState.DeserializeState () (at Assets/Arcadia/Components/ArcadiaState.cs:122)
ArcadiaState.Initialize () (at Assets/Arcadia/Components/ArcadiaState.cs:144)
ArcadiaStateEditor+InspectorCache.UpdateFrom (ArcadiaState state) (at Assets/Arcadia/Editor/CustomEditorInspectors.cs:85)
ArcadiaStateEditor.Refresh () (at Assets/Arcadia/Editor/CustomEditorInspectors.cs:152)
ArcadiaStateEditor.OnEnable () (at Assets/Arcadia/Editor/CustomEditorInspectors.cs:162)
```

I've noticed that this has to do with this line in `state_help.clj`:
`(edn/read-string {:readers *data-readers*} (.serializedData as))`

There doesn't seem to be a reader for vars.

Maybe this is intentional, but then how would I create roles with function vars in the state?
In this case I have a role that does something when colliding with a projectile, but I would like to put different functions there.

**Comment by Saikyun** [comment]
I am able to solve it by doing the following, but I it's really hacky, so don't really want to make a PR for it. Not sure how to deal with vars otherwise.

In `state_help.clj`:

```
(defn varify [x] (eval `(var ~x)))

(defn deserialize [^ArcadiaState as]
  (.BuildDatabaseAtom as true)
  (let [objdb (.objectDatabase as)]
    (binding [arcadia.data/*object-db* objdb]
      (try
        (let [^JumpMap jm (.state as)]
          (.Clear jm)
          (.AddAll jm
                   ;; in the future, switch on (.serializedFormat as)
                   ;; assuming edn for now
                   (edn/read-string
                    {:readers (assoc *data-readers*
                                     'arcadia.internal.state-help/varify
                                     varify)}
                    (str/replace
                     (.serializedData as)
                     "#'"
                     "#arcadia.internal.state-help/varify "))))
        (catch Exception e
          (Debug/Log "Exception encountered in arcadia.internal.state-help/deserialize:")
          (Debug/Log e)
          (Debug/Log "arcadia.data/*object-db*:")
          (Debug/Log arcadia.data/*object-db*)
          (throw (Exception. "wrapper" e)))))))
```

**Comment by timsgardner** [comment]
We don't currently have a good story for this. The problem is that it isn't completely clear how one should deserialize vars, in general, and no answer is baked into the language. For example, if a var is deserialized, should its namespace also be required? The best answer might well be something like what you have here, where readers are locally extended on deserialize, though it is difficult to do the same for serialization. That is, Clojure doesn't expose good robust thread-safe ways of locally modifying such serialization facilities as it has out of the box (eg, `pr-str`). The last time I looked at this problem vars seemed to be serializing not as `#'some-var` but as `(var some-var)`, though that may have changed in the interim, and unfortunately it is much more difficult to gracefully intervene on `print-method` than on the readers. In the past we tried to walk the deserialized-but-unevaluated data structure in State with `clojure.core/walk` and manually required and eval'd all instances of `(var some-var)`, but we pulled that because it's very hard to make fast, and it's very hard to do a walk like that for user-defined data structures loaded via tagged literals. We could expose some walk or recursive convert-vars protocol or multimethod or something for user data to extend, but didn't have the bandwidth to design that API and were unsettled by the prospect of introducing more complexity into our serialization system, especially to address this one very specific problem.

The current, rather unsatisfactory approach is to either:
- wrap vars in a user-defined data structure that knows how to serialize and deserialize itself via tagged literals
- use some other data abstraction that's easier to serialize and deserialize, such as a keyword that a multimethod dispatches on to replicate whatever logic would have consumed the var

That said, if vars have started serializing as "#'var" now, locally intervening on the reader might be a good solution. We have a prototype of a pseudo-hook allowing the user to wrap serialization and deserialization with dynamic var bindings, but we could also just introduce custom var deserialization logic ourselves.

**Comment by Saikyun** [comment]
Thanks for the lengthy answer. I see that it's not a straight forward problem to solve.

How are the vars in hooks serialized? E.g. `(hook+ go :start #'start)` works fine, so that's why I thought it'd work with state as well. :)

Thanks for the alternatives. I'll close this issue, since there doesn't really seem to be a good way to solve this cleanly. I do think however it might be worth suggesting alternatives in documentation/tutorials. :)
